CREATE TABLE alert_rules (
    enabled boolean NOT NULL,
    threshold double precision NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    window_seconds bigint NOT NULL,
    comparator varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    CONSTRAINT pk_alert_rules PRIMARY KEY (id)
);

CREATE TABLE alerts (
    acknowledged boolean NOT NULL,
    alert_id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_time timestamp(6) without time zone NOT NULL,
    resolved_time timestamp(6) without time zone,
    description text,
    evidence text,
    owner_placeholder varchar(255),
    recommendation_placeholder text,
    related_service varchar(255),
    related_span varchar(255),
    related_trace varchar(255),
    severity varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    CONSTRAINT pk_alerts PRIMARY KEY (alert_id)
);

CREATE TABLE saved_searches (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    last_used_at timestamp(6) without time zone,
    filters_json text NOT NULL,
    name varchar(255) NOT NULL,
    CONSTRAINT pk_saved_searches PRIMARY KEY (id)
);

CREATE TABLE services (
    first_seen timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    last_seen timestamp(6) without time zone NOT NULL,
    environment varchar(255),
    language varchar(255),
    service_name varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    version varchar(255),
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT uk_services_service_name UNIQUE (service_name)
);

CREATE TABLE traces (
    critical_path_duration_ms bigint,
    duration_ms bigint NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp(6) without time zone NOT NULL,
    http_method varchar(20),
    status_code varchar(20) NOT NULL,
    root_span_id varchar(32),
    exit_status varchar(40),
    trace_id varchar(64) NOT NULL,
    business_operation varchar(255),
    entry_endpoint varchar(255),
    evidence_graph_id varchar(255),
    request_uri varchar(255),
    root_span_name varchar(255) NOT NULL,
    service_name varchar(255) NOT NULL,
    status_message text,
    timeline_summary text,
    CONSTRAINT pk_traces PRIMARY KEY (id),
    CONSTRAINT uk_trace_trace_id UNIQUE (trace_id)
);

CREATE TABLE spans (
    http_status_code integer,
    duration_ms bigint NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp(6) without time zone NOT NULL,
    trace_entity_id bigint,
    http_method varchar(20),
    status_code varchar(20) NOT NULL,
    kind varchar(30) NOT NULL,
    parent_span_id varchar(32),
    span_id varchar(32) NOT NULL,
    trace_id varchar(64) NOT NULL,
    account_id varchar(255),
    customer_id varchar(255),
    loan_id varchar(255),
    name varchar(255) NOT NULL,
    service_name varchar(255) NOT NULL,
    status_message text,
    transaction_id varchar(255),
    CONSTRAINT pk_spans PRIMARY KEY (id),
    CONSTRAINT uk_span_trace_span UNIQUE (trace_id, span_id),
    CONSTRAINT fk_spans_trace_entity FOREIGN KEY (trace_entity_id) REFERENCES traces (id)
);

CREATE INDEX idx_alert_status ON alerts (status);
CREATE INDEX idx_alert_severity ON alerts (severity);
CREATE INDEX idx_alert_service ON alerts (related_service);
CREATE INDEX idx_alert_created ON alerts (created_time);

CREATE INDEX idx_span_span_id ON spans (span_id);
CREATE INDEX idx_span_trace_id ON spans (trace_id);
CREATE INDEX idx_span_parent_span_id ON spans (parent_span_id);
CREATE INDEX idx_span_service_name ON spans (service_name);
CREATE INDEX idx_span_name ON spans (name);
CREATE INDEX idx_span_kind ON spans (kind);
CREATE INDEX idx_span_duration ON spans (duration_ms);
CREATE INDEX idx_span_customer ON spans (customer_id);
CREATE INDEX idx_span_account ON spans (account_id);
CREATE INDEX idx_span_loan ON spans (loan_id);
CREATE INDEX idx_span_transaction ON spans (transaction_id);

CREATE INDEX idx_trace_trace_id ON traces (trace_id);
CREATE INDEX idx_trace_service_name ON traces (service_name);
CREATE INDEX idx_trace_start_time ON traces (start_time);
CREATE INDEX idx_trace_request_uri ON traces (request_uri);
CREATE INDEX idx_trace_http_method ON traces (http_method);
CREATE INDEX idx_trace_status_code ON traces (status_code);
CREATE INDEX idx_trace_business_operation ON traces (business_operation);
